'use strict';

const PROFILE_CONFIGS = {
  'default-walking': {
    id: 'default-walking',
    name: 'Default walking',
    description: 'General campus walking with mild accessibility penalties.',
    maxSlopeSoftPct: 8,
    maxSlopeHardPct: 18,
    slopeWeight: 1.0,
    maxSlopeWeight: 2.0,
    sustainedSlopeWeight: 1.0,
    crossSlopeWeight: 0.6,
    rollingResistanceWeight: 0.5,
    slipRiskWeight: 0.5,
    widthMinM: 0.9,
    widthPenaltyWeight: 0.8,
    stepFreeRequired: false,
    lightingMinScore: 0.3,
    lightingPenaltyWeight: 0.6,
    exposurePenaltyWeight: 0.2,
    crossingPenaltyWeight: 0.4,
    tactileBonusWeight: 0.2,
    crowdPenaltyWeight: 0.3,
    noisePenaltyWeight: 0.2,
    turnPenaltyWeight: 0.2,
    walkSpeedMps: 1.35
  },
  'manual-wheelchair': {
    id: 'manual-wheelchair',
    name: 'Manual wheelchair',
    description: 'High sensitivity to slope, width, and step-free constraints.',
    maxSlopeSoftPct: 4.5,
    maxSlopeHardPct: 8,
    slopeWeight: 4.8,
    maxSlopeWeight: 8.0,
    sustainedSlopeWeight: 7.0,
    crossSlopeWeight: 5.0,
    rollingResistanceWeight: 3.8,
    slipRiskWeight: 3.5,
    widthMinM: 1.2,
    widthPenaltyWeight: 6.0,
    stepFreeRequired: true,
    lightingMinScore: 0.45,
    lightingPenaltyWeight: 1.2,
    exposurePenaltyWeight: 0.6,
    crossingPenaltyWeight: 2.0,
    tactileBonusWeight: 0.4,
    crowdPenaltyWeight: 0.8,
    noisePenaltyWeight: 0.3,
    turnPenaltyWeight: 1.0,
    walkSpeedMps: 0.85
  },
  'powered-wheelchair': {
    id: 'powered-wheelchair',
    name: 'Powered wheelchair',
    description: 'Step-free required with moderate sustained slope tolerance.',
    maxSlopeSoftPct: 6,
    maxSlopeHardPct: 10,
    slopeWeight: 3.0,
    maxSlopeWeight: 5.0,
    sustainedSlopeWeight: 3.0,
    crossSlopeWeight: 3.0,
    rollingResistanceWeight: 2.0,
    slipRiskWeight: 2.3,
    widthMinM: 1.1,
    widthPenaltyWeight: 4.5,
    stepFreeRequired: true,
    lightingMinScore: 0.4,
    lightingPenaltyWeight: 1.0,
    exposurePenaltyWeight: 0.5,
    crossingPenaltyWeight: 1.6,
    tactileBonusWeight: 0.3,
    crowdPenaltyWeight: 0.7,
    noisePenaltyWeight: 0.3,
    turnPenaltyWeight: 0.8,
    walkSpeedMps: 1.0
  },
  'mobility-scooter': {
    id: 'mobility-scooter',
    name: 'Mobility scooter',
    description: 'Sensitive to narrow paths, steep ramps, and sharp turns.',
    maxSlopeSoftPct: 5.5,
    maxSlopeHardPct: 11,
    slopeWeight: 2.6,
    maxSlopeWeight: 4.8,
    sustainedSlopeWeight: 3.8,
    crossSlopeWeight: 2.5,
    rollingResistanceWeight: 2.4,
    slipRiskWeight: 2.0,
    widthMinM: 1.15,
    widthPenaltyWeight: 5.8,
    stepFreeRequired: true,
    lightingMinScore: 0.35,
    lightingPenaltyWeight: 0.8,
    exposurePenaltyWeight: 0.5,
    crossingPenaltyWeight: 1.2,
    tactileBonusWeight: 0.2,
    crowdPenaltyWeight: 0.6,
    noisePenaltyWeight: 0.2,
    turnPenaltyWeight: 3.2,
    walkSpeedMps: 1.1
  },
  crutches: {
    id: 'crutches',
    name: 'Crutches',
    description: 'Penalizes sustained slope, descents, and uneven surfaces.',
    maxSlopeSoftPct: 6,
    maxSlopeHardPct: 12,
    slopeWeight: 3.2,
    maxSlopeWeight: 3.6,
    sustainedSlopeWeight: 4.7,
    crossSlopeWeight: 3.3,
    rollingResistanceWeight: 3.1,
    slipRiskWeight: 3.5,
    widthMinM: 1.0,
    widthPenaltyWeight: 2.8,
    stepFreeRequired: false,
    lightingMinScore: 0.4,
    lightingPenaltyWeight: 1.0,
    exposurePenaltyWeight: 0.6,
    crossingPenaltyWeight: 1.0,
    tactileBonusWeight: 0.2,
    crowdPenaltyWeight: 0.8,
    noisePenaltyWeight: 0.3,
    turnPenaltyWeight: 0.5,
    descentWeight: 1.8,
    walkSpeedMps: 0.9
  },
  'blind-low-vision': {
    id: 'blind-low-vision',
    name: 'Blind or low vision',
    description: 'Avoids unsafe crossings and prefers tactile guidance.',
    maxSlopeSoftPct: 8,
    maxSlopeHardPct: 16,
    slopeWeight: 1.6,
    maxSlopeWeight: 2.3,
    sustainedSlopeWeight: 1.7,
    crossSlopeWeight: 1.2,
    rollingResistanceWeight: 0.9,
    slipRiskWeight: 1.4,
    widthMinM: 1.0,
    widthPenaltyWeight: 1.2,
    stepFreeRequired: false,
    lightingMinScore: 0.5,
    lightingPenaltyWeight: 2.6,
    exposurePenaltyWeight: 0.9,
    crossingPenaltyWeight: 5.0,
    tactileBonusWeight: 2.2,
    crowdPenaltyWeight: 1.1,
    noisePenaltyWeight: 0.6,
    turnPenaltyWeight: 0.4,
    walkSpeedMps: 1.05
  },
  'sensory-sensitive': {
    id: 'sensory-sensitive',
    name: 'Sensory sensitive',
    description: 'Placeholder hooks for crowd and noise-aware routing.',
    maxSlopeSoftPct: 8,
    maxSlopeHardPct: 16,
    slopeWeight: 1.4,
    maxSlopeWeight: 2.1,
    sustainedSlopeWeight: 1.6,
    crossSlopeWeight: 1.0,
    rollingResistanceWeight: 0.8,
    slipRiskWeight: 0.8,
    widthMinM: 1.0,
    widthPenaltyWeight: 1.0,
    stepFreeRequired: false,
    lightingMinScore: 0.4,
    lightingPenaltyWeight: 1.0,
    exposurePenaltyWeight: 1.2,
    crossingPenaltyWeight: 0.8,
    tactileBonusWeight: 0.2,
    crowdPenaltyWeight: 4.5,
    noisePenaltyWeight: 4.0,
    turnPenaltyWeight: 0.4,
    walkSpeedMps: 1.0
  }
};

const PROFILE_LIST = Object.values(PROFILE_CONFIGS).map((profile) => ({
  id: profile.id,
  name: profile.name,
  description: profile.description
}));

function getProfileConfig(profileId) {
  const key = String(profileId || '').trim().toLowerCase();
  if (!key) return PROFILE_CONFIGS['default-walking'];
  return PROFILE_CONFIGS[key] || PROFILE_CONFIGS['default-walking'];
}

function listProfiles() {
  return PROFILE_LIST;
}

module.exports = {
  PROFILE_CONFIGS,
  getProfileConfig,
  listProfiles
};
