ALTER TABLE edge_slope_samples ADD COLUMN IF NOT EXISTS measurement_quality DOUBLE PRECISION;
ALTER TABLE routing_edges ADD COLUMN IF NOT EXISTS spot_check_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE routing_edges ADD COLUMN IF NOT EXISTS spot_check_last_at TIMESTAMPTZ;
